name: Minha Primeira Linha de Montagem

on:
  push:
    branches: [ main ]

jobs:
  build-e-teste:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4

      - name: 2. Executar Teste e Gerar Identificador
        run: echo "Construindo o projeto... Verificando se todas as peças se encaixam!"

      - name: 3. Disponibilizar Artefato.
        run: echo "Rodando os testes automatizados... Verificando se a porta abre e fecha!"
